### PR TITLE
Add back to top button on Home page

### LINKED ISSUE #423: A button to navigate to the Top of the page
### Description

The Home page can use a back to the top button to navigate back to the top
Extra : The button only appears when u scroll down to a certain point of the page and not at the start of the page itself so as to keep the image part clean
Please assign me this issue

### Screenshots

_No response_

### Additional information

_No response_

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Rohan-Hazari**
# Fixes Issue #423 

**My PR closes #423 **

# Changes proposed

## What were you told to do ?

Add a button with Minimal design to navigate back to top of the page only for the Home page

## What did you do ?

Added the button with the above functionalities
It only appears when you scroll on a bit on the page keeping the landing visual clean

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

image

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image

- Can we reduce the size of the cirlce ? It looks too big
- Can we change the color of the arrow from black to the same color of the explore button !

**Comment by Rohan-Hazari** [comment]
image
Is this small enough?

**Comment by Rohan-Hazari** [comment]
Also centered the arrow vertically

image

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Comment by Rohan-Hazari** [comment]
Hey am I suppose to do a pull request again with the updates because i see the updates have been automatically committed here

**Pull request merged**
