### PR TITLE
fix: Modify mobile styling for footer

### LINKED ISSUE #236: UI/UX - Footer for mobile 🎨
### Take a look at the footer in mobile screens

The footer looks bad specially because it is cramped up.
- The width of the text can be increased so that it spreads
- The fontsize can be decreased by maybe 1/2 pixels ? 
- Also refer to **Image2**, i want them side by side for **mobiles**

### Image 1

image

### Image 2

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kristiingco**
# Issue  📐

- **I, Kristi Ingco, have worked for 236 *

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #236 **

## Screenshots 📷

**Here are the pictures of changes that I have made 🔽**

Footer for Samsung Galaxy S20 Ultra
image

Footer for iPhone SE 
image

Footer for Pixel 5
image

  
  
---

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
### I would like to have some changes ! 

image

 - Can i have the `join` button to the left more ?

**Comment by kristiingco** [comment]
> ### I would like to have some changes !
> image
> 
> * Can i have the `join` button to the left more ?

got it! pushed a new commit [5a3c4e3](https://github.com/IAmTamal/Milan/pull/249/commits/5a3c4e330529b2157b078e587a68082704901ca1) that addresses this. should look like this

image

**Comment by IAmTamal** [comment]
Looks good to me !

**Review by IAmTamal — APPROVED** [review]
Checked ✅

**Pull request merged**
