### PR TITLE
Improved Footer of home page

### LINKED ISSUE #376: Improving footer of the website
### Description

Hey @IAmTamal , The footer of website is not matching with the theme, I want to improve its styling and add some hover effect on buttons so that it matches the theme of the whole website. Can you please assign me this issue so that I can work on it. Thank you!

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Issue  📐

- **I Sumit Kumar have worked for issue number 376**

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #376**

Hey @IAmTamal I have made changes in the footer as I told you earlier. You can take a glimpse on it. 

- Before:- (Didn't mathced with the theme and divs were not aligned properly, icons were vey small)

Screenshot (359)

- After:- (Macthed with theme, aligned every div, added hover effect, added font awesome icons)

[video.webm](https://user-images.githubusercontent.com/100675296/194149249-82277e09-9721-4ced-b89e-5594bf6e9ffb.webm)

Hope you like it. Please let me know if there is any changes to be made. Thank you!
  
---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Hi there some changes needs to be done : 


 - Remove those Login, register button and replace them with the text we had before.
 - The social icons are too big, reduce their size
 - The social icons donot work at all, they should work properly (take a look at original site)
 - The icons are not properly circled and alligned : 
image

- The report button should be of the same color as it was, remove the hover (box shadow) but keep that bug animation.
- Also socials should look good on mobiles too : 
image

**Comment by sumitkr2000** [comment]
@IAmTamal  ok i will get back after making the changes u have told.

**Comment by sumitkr2000** [comment]
Hey @IAmTamal I have successfully made the changes that you have told. Please view the letest deployment and review it. Hopw now everything is working fine. Thank you!

**Comment by sumitkr2000** [comment]
@IAmTamal Now please check.

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
