### PR TITLE
Updated Validation Methods For user's Login & Register

### LINKED ISSUE #449: Regestration And Login Email Validation
### Description

Email validation on both login and regestration pages are allowing email input like `user@gmail` where it should be not allow email withoouth tld. 

### Screenshots

image

### Additional information

We can improve the validation function

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Tineshnehete**
# Fixes Issue

My PR closes #449 

# Changes proposed
I upgraded the validation methods for Loging And regestration pages .
It added to dependencies to pakage.json
[Jsonschema : data validation library ](https://www.npmjs.com/package/jsonschema) 
[Url - requered for jsonschema ](https://www.npmjs.com/package/url)
## What were you told to do ?
We discussed to update the email validation method .As it allows to invalid email inputs .

## What did you do ?
I upgraded validation method for login and regestration form .
Note : it is upgraded on changeevent handler and submit event handler

---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image

Instead of blocking out the button why not keep the button enabled
Tell the user with the toast to `Provide a valid Email` ?

**Comment by Tineshnehete** [comment]
Ohh yes 😉. Implementing it .

**Comment by Tineshnehete** [comment]
Hi dont know why cypress is failed.

**Comment by Tineshnehete** [comment]
It Passed here https://github.com/Tineshnehete/Milan/actions/runs/3228646999/jobs/5294756087 .

**Review by IAmTamal — CHANGES_REQUESTED** [review]
@Tineshnehete Donot worry about Cypress, i wrote some wrong code. It will be fixed. 

- i need some changes, take a look at this video below.
- As you can see if i click on blank inout fields or have partially filled inputs it keeps showing the errors.
- Make it so that the toasts are shown ONLY when we click the button. 
- The button needs not to be disabled, it was previously disabled because we were not checking as you did. 
- If someone gives invalid email, and then press on the button, it should show `Please provide a valid mail`

**Comment by Tineshnehete** [comment]
Means validation only on submit ?

**Comment by IAmTamal** [comment]
> Means validation only on submit ?

Yes. Like instead of checking all the time, check at the end. 
If valid, okay. 
If not, show message

**Comment by Tineshnehete** [comment]
> te some w



> > Means validation only on submit ?
> 
> Yes. Like instead of checking all the time, check at the end. If valid, okay. If not, show message

yes done it

**Comment by IAmTamal** [comment]
> > > Means validation only on submit ?
> > 
> > 
> > Yes. Like instead of checking all the time, check at the end. If valid, okay. If not, show message
> 
> yes done it

Do push the codes - i don't see any changes

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
