### PR TITLE
fix: footer elements not centered

### LINKED ISSUE #1072: [BUG] Footer elements not centered on screens <768 pixels
### Description

When accessing the https://milanhub.org/ on screens with a width less than 768 pixels, certain elements within the footer do not maintain their centered alignment as intended.

## Expected behavior:
The highlighted elements in the footer should be centered on the screen when the screen size is less than 768 pixels

### Screenshots

milan

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

### PR DESCRIPTION
**Pull request by ghost**
closes #1072 

### 👷🏻 Changes made  

comment out the css style of class join-us-list

### Before
after

### After
Screenshot (228)

### CODE REVIEW

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Love the changes that have been made however, I would love to have some more minor fixes if you are willing to. 

 - Can you please remove the `Contact Us` from the footer
 - And replace the text for the report from:
 - - `GOT SOMETHING TO REPORT ?` -> `TALK TO US`
 - - `You can submit a report to us by filling the form below !` -> `Ideas, problems, violations ? Reach out to us !`
 - - Finally the button can be changed from `Report` to ` Contact Us`

**Comment by Utkarsh3128** [comment]
Sure, Sir I would love to work on this.

**Comment by Utkarsh3128** [comment]
@tamalCodes Sir, I have made changes as per your request.

**Review by tamalCodes — APPROVED** [review]
# Amazing work 🎉
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/MilanCommunity/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Pull request merged**
