### PR TITLE
Fix: Login/register page design issues

### LINKED ISSUE #397: Login page design different
### Description

- While continue as login as club, Login page design is different to register page.
- In login page purple color is used but blue color should be used.

### Screenshots

image

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nishtha53**
#397 

# Fixes Issue

**My PR closes #397**

# Changes proposed

## What were you told to do ?

 - Register button color changed to purple.
 - Login text changed from Log in to  Log in with your club!

## What did you do ?

- Register button color changed to purple.
- Login text changed from Log in to  Log in with your club!
Additional fixes:
- In login page, gave remember fix checkbox color to purple.
- Input field focus color change to purple for both login register page.
- Added label in login page same as register page for Email and password

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

image
image

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image

- Please change the color of `/user/register` to what it was before
- Please add emojis beside `Email address` , `password` in `/user/register`
- Make sure it is the same emoji as in clubs register

**Comment by nishtha53** [comment]
okay sure i will do following changes.

**Comment by nishtha53** [comment]
@IAmTamal before creating PR, I have one question in mobile view we are not keeping labels for input fields??

**Comment by nishtha53** [comment]
image
image
image
image


Also, changes are fixed.

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Comment by nishtha53** [comment]
Thankyou!

**Pull request merged**
