### PR TITLE
dark/light mode

### PR DESCRIPTION
**Pull request by NageshMandal**
#324   📐

- **I <Nagesh Mandal>Dark/Light Mode<#324>

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
There are alot of bugs - fix it ! 

- DONOT DELETE STUFFS FROM THE PR TEMPLATE
- The button is outof no-where
- The text `Where HELP meets NEED` has a different color
- Dark mode doesnot work
- Dark mode is not visible in other pages

**Comment by NageshMandal** [comment]
Uploading 03.10.2022_15.25.56_REC.mp4…

**Comment by NageshMandal** [comment]
could you please review the code @IAmTamal

**Comment by IAmTamal** [comment]
> could you please review the code @IAmTamal

Hello , IDK how to break it to you, but everything **LOOKS BROKEN**

## Examples : 

The Button is out of place, put it in the navbar. The text is blue, idk why.
image

Donot change the picture , it can be what it is
image

These looks very weird 
image

**Comment by IAmTamal** [comment]
I thought initially the app would look better in dark mode, but since there's alot of changes specially related to designing i'll close the PR. We need to even make a new Figma file / design for the app since all the components needs to be custom designed.

You can work on other issues. 
Closing this one.

**Comment by IAmTamal** [comment]
I thought initially the app would look better in dark mode, but since there's alot of changes specially related to designing i'll close the PR. We need to even make a new Figma file / design for the app since all the components needs to be custom designed.

You can work on other issues. 
Closing this one.

**Pull request closed without merging**
