### PR TITLE
Added Automated Cypress Tests to Github Workflows

### LINKED ISSUE #431: 🔴 [Automations] - Configure a Github actions for Cypress Test 🛠
## Test files : 

 - The test files are located [here](https://github.com/IAmTamal/Milan/tree/main/cypress/e2e)

## Actions ? 

- Write a GitHub action so that whenever a push /PR is made to the GitHub repo the github workflow is triggered
- And all the tests are performmed and checked
- This is a high priority issue !

### PR DESCRIPTION
**Pull request by JulianaSau**
# Fixes Issue

**My PR closes #431**

# Changes proposed

## What were you told to do ?

1. Write a GitHub action so that whenever a push /PR is made to the GitHub repo the github workflow is triggered
2. And all the tests are performed and checked

## What did you do ?

---

1. I edited the `cypress.config.json` file to search for tests in the cypress folder
2. I created a `cypress-tests.yml` file under `cypress/e2e` folder that contains the github actions that sets up a docker container, installs dependencies, builds the project, starts the project then runs the neccessary tests found in the `cypress/e2e` folder
3. I cleared the warnings in different files of the project as the jobs were failing due to the `eslint` warnings being treated as errors thus triggering a job fail error.
4. Set `CI` to `false` as a temporary fix to the workflow failing when it encounters `eslint` warnings

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

image

### CODE REVIEW

**Comment by IAmTamal** [comment]
@JulianaSau I see you fixed out ALOT of warnings which would have appeared in the console and stuffs. 

- My question is if there are any warnings, will the test fail ? 
- If yes, can it be made such that tests donot fail for warnings, because newbies may write codes which gives warnings like using `class` instead of `className`

**Comment by JulianaSau** [comment]
If there are warning in the project it will fail. Because CI is set to true.

It can be done. In other projects I've done, setting the environment variable to CI=false is a temporary fix for it. An alternative is editing the eslint config to see any unused variables as errors so that the contributor won't any push code that has "warnings". Also running a linter using husky pre-push/pre-commit to fix newbie errors such as the ones you mentioned could work.

**Comment by IAmTamal** [comment]
> If there are warning in the project it will fail. Because CI is set to true.
> 
> It can be done. In other projects I've done, setting the environment variable to CI=false is a temporary fix for it. An alternative is editing the eslint config to see any unused variables as errors so that the contributor won't any push code that has "warnings". Also running a linter using husky pre-push/pre-commit to fix newbie errors such as the ones you mentioned could work.

I see, so for now can we make CI false ? 

- Also since you said `CI false` is  a temporary fix, can you make another issue and work on `linter using husky pre-push/pre-commit` ? 
- That would be great because often times there's problem with warnings and stuffs, and it would fail. We can always fix the warnings later.

**Comment by JulianaSau** [comment]
Sure. I think setting CI to false will work for now. I'll inform you once I've done so.

I'll create the issue for setting up the linter and send in a PR sometime this week.

**Comment by JulianaSau** [comment]
@IAmTamal I've managed to set CI to false. The workflow now runs even if `eslint` warnings are present😁

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
