### PR TITLE
feat: add signup popup

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
## Related Issue 

Closes: #652 

#### Describe the changes you've made ✍
This PR adds a signup popup containing two buttons whether to sign up as an individual or as a club.

#### Screenshots (if any) 📸
https://user-images.githubusercontent.com/88369802/235648646-90b4ec21-1095-4a47-973a-98a220db6226.mov

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Hi @Syed-Ali-Abbas-Zaidi , great work but let's talk about some changes that would be needed in the feature.

image

- The color of the text can be `#000000` instead of white.
- Please remove the small icons. 
- Please remove the line between the 2 buttons, and instead of `Sign Up as an` change it to `Continue as a`
- Also we can instead say `Club/NGO` instead of just `Club` & `User` instead of `Individual`
- Also for the `h1` I recommend using `font-family: Poppins,sans-serif;` instead , also make it bold if possible.

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> Hi @Syed-Ali-Abbas-Zaidi , great work but let's talk about some changes that would be needed in the feature.
> 
> image
> 
> * The color of the text can be `#000000` instead of white.
> * Please remove the small icons.
> * Please remove the line between the 2 buttons, and instead of `Sign Up as an` change it to `Continue as a`
> * Also we can instead say `Club/NGO` instead of just `Club` & `User` instead of `Individual`
> * Also for the `h1` I recommend using `font-family: Poppins,sans-serif;` instead , also make it bold if possible.

I have implemented your suggestions. Please review.

**Comment by IAmTamal** [comment]
Hey @Syed-Ali-Abbas-Zaidi , the changes look good. Just change the `h1` to `#000000` instead. And also I just checked , we have another [Modal](https://github.com/IAmTamal/Milan/blob/main/src/components/Modal.jsx) component already made, which was added in #615 

I want to ask, is it possible that instead of the new Modal file we are creating, we use that instead ? 
This way there will be less amount of files & always we would be re-using the components !

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @IAmTamal, I am using the [Modal](https://github.com/IAmTamal/Milan/blob/main/src/components/Modal.jsx) component in my `SignUpModal` file. The thinking behind creating a separate file was that the modal triggers from two different places `Banner` and `NavBar`, so the code will get repeated, and if we had to make a change in `SignUpModal` we had to make the change at two different places. That is why I created a new component.

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Closing this PR due to too many commit issues. I have created this new [PR](https://github.com/IAmTamal/Milan/pull/664).

**Pull request closed without merging**
