### PR TITLE
Update CONTRIBUTING.md 

### LINKED ISSUE #435: [DOCS] <description>
### Description

There are some grammar mistakes as well as some improvements in the CONTRIBUTING.md file. This thing can be fixed to make file more interactive and as well as more readable.

### Screenshots

Screenshot 2022-10-09 at 6 57 32 AM

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by dev-32**
# Fixes Issue

**My PR closes #435**

# Changes proposed

## What were you told to do?

To change and remove the line, and correct the grammar mistakes.

## What did you do?

Changes the things that are assigned to me and also improved all the grammar corrections.

---

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR are clear and explain the approach.

# Screenshots

Screenshot 2022-10-09 at 10 28 32 AM

### CODE REVIEW

**Comment by dev-32** [comment]
I have written in the changes proposed but I think, it has not been written. Since I am a beginner, please don't mind it.
1) What were you told to do?
Ans.) I have to remove lines and improved the grammar mistakes in the CONTRIBUTING.md file.

2)What did you do?
Ans.) I have done the assigned work and also updated all the grammar mistakes.

**Comment by IAmTamal** [comment]
> I have written in the changes proposed but I think, it has not been written. Since I am a beginner, please don't mind it.
> 
> 1. What were you told to do?
>    Ans.) I have to remove lines and improved the grammar mistakes in the CONTRIBUTING.md file.
> 
> 2)What did you do? Ans.) I have done the assigned work and also updated all the grammar mistakes.

That is because whenever we write something between <!-- it becomes a comment
Also from the next time write issue number like this 
image


If i MERGE this PR, the ISSUE WILL be closed automatically because we are using the word `closes` before the issue number

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Comment by dev-32** [comment]
Sure, I will take care next time. Thank you !!

**Pull request merged**
