### PR TITLE
Banner text #14  

### PR DESCRIPTION
**Pull request by Rohan-Hazari**
Hey @IAmTamal  I did everything that was asked
Changed the text to Uppercase,
made the font size bigger, 
made the keywords bolder,
improved the text style and gave a text-shadow so the text stands out a bit more
I also gave it a media query since the bigger font size was breaking it at smaller screen size 
Also, the buttons were looking unsymmetrical so to make them look symmetrical I gave a width to the smaller one

BEFORE
Screenshot 2022-02-01 173135

AFTER
Screenshot 2022-02-01 153414

### CODE REVIEW

**Comment by Rohan-Hazari** [comment]
Hey I committed the project twice since this was my first time sorry if that causes any trouble

**Comment by IAmTamal** [comment]
That looks awesome ,  can you please increase the font weight og the word "MILAN" ?

**Comment by Rohan-Hazari** [comment]
Ok

**Comment by Rohan-Hazari** [comment]
So I only had to commit right or do I have to pr again?
This much font-weight is enough right cuz any bolder than this would look ugly
image

**Comment by IAmTamal** [comment]
Yeah that Looks perfect !!

**Pull request merged**
