### PR TITLE
Successfully Removed Bug regarding labels and placeholders

### PR DESCRIPTION
**Pull request by devwithsubhrajit2002**
# Fixes Issue #530

**My PR closes #issue_number_here**

# Changes proposed
Made the create event page responsive to screen size or width to add or remove placeholders and adding labels for desktop view.
## What did you do ?

---

# Check List (Check all the applicable boxes)

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.

# Screenshots

### CODE REVIEW

**Comment by devwithsubhrajit2002** [comment]
@IAmTamal please merge this pull request. You will see 1 test which is a deployment error but I have correctly modified the code to work as you wish. There will be no problem after merging I assure you from my side.

**Review by IAmTamal — CHANGES_REQUESTED** [review]
@devwithsubhrajit2002  If a Cypress test is failing that means there is something wrong with the code you have provided in the PR. Do fix it.

image

Always do check the logs for more details.

**Comment by devwithsubhrajit2002** [comment]
Please help I cannot see the logs
@IAmTamal

**Comment by devwithsubhrajit2002** [comment]
At least Approve the review so that it counts in my Hacktoberfest contribution. I would lose the opportunity to get the last badge.

**Review by IAmTamal — APPROVED** [review]

**Comment by IAmTamal** [comment]
make sure you do the changes by then. This is a VERY UNETHICAL WAY.

**Comment by devwithsubhrajit2002** [comment]
Ok I will give the best @IAmTamal

**Comment by IAmTamal** [comment]
> Ok, I will give the best @IAmTamal Thank you sir for approving and getting me the last badge of hacktoberfest.

Do make the changes and push it

**Comment by devwithsubhrajit2002** [comment]
ok sir.

**Pull request closed without merging**
