### PR TITLE
fix: UI fix in user register page

### LINKED ISSUE #172: 🎨 UI/UX - User Register Page
## I want to make some changes to the clubs and user's Login page
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**Currently this is how the page looks⤵**

image

**⭐ I want the placeholders to be removed from the red dash marked input fields**
**⭐ I want  the `Firstname` and `Lastname` to be side by side instead of how they are now**
**⭐ Firstname and Lastname should have their place holder**
**⭐ I want a label for them `Enter your name`**
**⭐ Also reduce spaces between the Labels and the Input fields !!**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

### PR DESCRIPTION
**Pull request by Aniket-508**
# Issue name

- **I Aniket Pawar have worked for this issue under JWOC**

[put x to check the boxes]: <> (This is a comment, it will not be included)   
## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet** 
- [x] **Setup Guidelines**
- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #172 **
  
  
## Screenshots 📷
  
**Here are the pictures of changes that i have made⤵**
  
Screenshot (29)
Screenshot (30)

  
  
  
---

### CODE REVIEW

**Comment by IAmTamal** [comment]
@Aniket-508  , can you make it so for **MOBILES** the input fields for first and last name are big ?

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Changes mentioned in above comment.

**Comment by Aniket-508** [comment]
You did not told that, as per the issue. But sure will do the changes requested. Can you please assign it as medium since I have to figure out register? @IAmTamal

**Comment by IAmTamal** [comment]
> You did not told that, as per the issue. But sure will do the changes requested. Can you please assign it as medium since I have to figure out register? @IAmTamal

The register works fine !! 

I just told you since you made a lot of code changes , it should not break.

**Comment by Aniket-508** [comment]
try to configure prettier or any other formatter precommit in package json so that every code that is uploaded in Prettier format, I used that which i why so many lines are changed @IAmTamal

**Comment by Aniket-508** [comment]
@IAmTamal Completed with the requested change.

**Pull request merged**
