### PR TITLE
Fix : Updates to textareas and copyrights 🛠

### LINKED ISSUE #345: Feature: Adding Text Area Instead Of Text Fields In Address Section
### Description

address

The Address section must be a "text area" instead of a text field. And also its a tradition of mentioning Address in Text Area so that users can specify their address more accurately.

Hey, @IAmTamal Please assign me with this issue.

Thanks!

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RishitaGangwal**
# 347  📐

- **I  Rishita Gangwal have worked for #345 #344 **

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #345 #344 **

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hi @RishitaGangwal we have 2 PRs #363 and #347 

We need to have just one so that you can get your hacktoberfest contributions.

- The changes are perfect, howver for mobiles, please add a margin top of atleast 15px
image

**Comment by RishitaGangwal** [comment]
Done with the changes.

**Comment by RishitaGangwal** [comment]
Hey, now changes are okay?

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
