### PR TITLE
Added TextArea in Address Section and Copyright Notice at the bottom of the website!

### LINKED ISSUE #345: Feature: Adding Text Area Instead Of Text Fields In Address Section
### Description

address

The Address section must be a "text area" instead of a text field. And also its a tradition of mentioning Address in Text Area so that users can specify their address more accurately.

Hey, @IAmTamal Please assign me with this issue.

Thanks!

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RishitaGangwal**
#345   📐

- I Rishita Gangwal have worked for #345 #344 

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #345 #344 >**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
  
  
---TextArea

address1

Copyright

copyright

css

output

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by RishitaGangwal** [comment]
I have made some changes in above coding! Please check this code.

address1

**Review by IAmTamal — CHANGES_REQUESTED** [review]
## IMPORTANT 

- Donot make any changes to `index.html` or `index.css`
- If you need to add something, make a new component in the components folder and then add it.
- For styles, you can make a new file too.

## Changes : 

image

- There is  a white box type of thing. Remove that.
- There must be no gap between Footer and Copyright section
- The copyright's background color must be the same as footer section.

## Changes related to text-area

- Make sure the style of the text area is the same as that of what we used in `/clubs/register`
- Make sure it looks good on mobiles

**Comment by RishitaGangwal** [comment]
So, should I make another component right nor or from the next time?

**Comment by IAmTamal** [comment]
> So, should I make another component right nor or from the next time?

Every changes that i suggested in the previous comment is for the **current and future PRs to this Project**

**Comment by RishitaGangwal** [comment]
CHANGES SECTION:

changes1

changes

I have changed styling according to Change Request Part.

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Hi there, we'd still need some changes : 

## Changes : 

- Remove white space, it looks bad 
image

- Remove Copyright warning from pages that **doesnot have a footer**
image

**Comment by RishitaGangwal** [comment]
Change Requested:

changes2

I have made changes according to your request.

**Comment by IAmTamal** [comment]
@RishitaGangwal You don't need to post Screenshots - we have vercel preview feature setup. 
Just push the changes to the PR.

I cannot see any latest changes. It's the same as it was. push them to the repo.

**Comment by RishitaGangwal** [comment]
Now it's done?
It's creating another PR.

**Pull request closed without merging**
