### PR TITLE
Added Hover on Explore & Share Buttons(#369 Solved)

### LINKED ISSUE #369: Hover Feature on Explore & Share Buttons
### Description

While going through the UI of website , I found that few buttons like 'Explore' and 'Share you Love' is lacking with hover effect.
I want to work on this bug and want to fix it under Hacktoberfest'2022 label. 

Please assign me this issue !!

### Screenshots

image
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aakashraj01**
# Issue 369 📐

- **I Aakash Raj have worked for** #369 

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #369**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>

  Before
  
Untitled video - Made with Clipchamp

After
Untitled video - Made with Clipchamp (1)
  
---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Hi there can you also apply the same hover in `/shops/shop` page ?

**Comment by aakashraj01** [comment]
> Hi there can you also apply the same hover in `/shops/shop` page ?

hey @IAmTamal Done adding hover effect on shop button in shops/shop.
Can you now merge this under hacktoberfest'22-accepted label. :)

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
