### PR TITLE
Added hover effect on the product cards

### LINKED ISSUE #447: Zooming on hovering on the products
### Description

In the shop section, when we hover over the products we can apply the zooming animation to make it look more interactive.

### Screenshots

image

### Additional information

The above screenshot attached is what it will look like if we hover over the images.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by wickedwisdom0911**
# Fixes Issue

**My PR closes #447**

# Changes proposed
Added box shadow and cursor pointer on hover over the product cards

## What were you told to do ?

Was told to put a box shadow of color "#297f75" and a cursor pointer on the hover

## What did you do?

Added box shadow of the color "#297f75 and a cursor pointer on the hover
---

# Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

# Screenshots

image

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image


- Make the transitions smooth, it feels bad when hovering over them. Make the hover effects smoother.
- Why is the green shadow only on the image ? Add it to the full product card.
- The shadow is pointy, but the card is not , fix that too.

**Comment by wickedwisdom0911** [comment]
Okay will get to it tamal.

**Comment by wickedwisdom0911** [comment]
Done with the smooth transitions and added them on the whole product card. If still not up to point , i will work on it more

**Comment by wickedwisdom0911** [comment]
Hey, tamal can you guide me on how to fix this EZE test that is failing on chrome? I can't figure it out . I just added the hover effect i was assigned

**Comment by IAmTamal** [comment]
> Hey, tamal can you guide me on how to fix this EZE test that is failing on chrome? I can't figure it out . I just added the hover effect i was assigned

Donot worry i had some buggy code and as a result stuffs were failing.
Do let me know once all the changes are done, because as i can see from the deploy preview there are still some bugs and glitches

**Comment by wickedwisdom0911** [comment]
Oh I will look over it. And tell you. The deploy preview was working fine
then. I will check it once again

**Comment by IAmTamal** [comment]
@wickedwisdom0911 


image
- The shadow is dense at the bottom, while almost not visible at the top
- Make it even on all sides, not too dense like in the bottom.

**Comment by wickedwisdom0911** [comment]
Okay will get to it

**Comment by wickedwisdom0911** [comment]
Please look over it tamal and let me know if any more changes are required. Thanks

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
