### PR TITLE
Changes in Headers

### LINKED ISSUE #297: Accessibility - Changes in Headers
### Description

 - Take a look at the web app, you'll find that we are using **alot of h1, h2 and so on**
 - Make sure we use it in a proper manner. 
 - Like in a div, if there are 2 headers we should have **H1 first, and then H2** , not **H3, then H1 and so on**
 - Make sure the font sizes remains the same, you just need to make changes to the tag ! 

## Here's what i am talking about  
image
image

- As you can see we have **H3 first, H1 second** - we should not have these !

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by 4k5h1t**
# Issue  📐

- **I Akshit have worked for #297 **

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **This pull request closes #297  **

  
  
  
---

### CODE REVIEW

**Comment by 4k5h1t** [comment]
Should be completed now

**Comment by 4k5h1t** [comment]
Looks good ? Can we close this issue ?

**Comment by IAmTamal** [comment]
> Looks good ? Can we close this issue ?

i want to ask something , 

### This is the original site : 
image

### This is what the preview is giving me : 
image


You sure, the CSS isn't messed up ? 
Because alot of places have CSS like : 

```
.name_of_the_div h3

```

**Now that we have h1 , and so on - please make sure the site headers looks EXACTLY the same as of the DEPLOYED ONE **

**Review by IAmTamal — CHANGES_REQUESTED** [review]
### i want to ask something , 

### This is the original site : 
image

### This is what the preview is giving me : 
image


You sure, the CSS isn't messed up ? 
Because alot of places have CSS like : 

```
.name_of_the_div h3

```

**Now that we have h1 , and so on - please make sure the site headers looks EXACTLY the same as of the DEPLOYED ONE**

**Comment by 4k5h1t** [comment]
Oooohk got it, sorry, will fix

**Comment by 4k5h1t** [comment]
Ok so, it's not that it got messed up. It is working like it's supposed to but I'll need to modify what h1, h2, etc means (in terms of font style, size, color etc), if you want to have the headers in ascending order and still keep the original look. Sound good ?

**Comment by IAmTamal** [comment]
> 

Yes , i want to have all the headers in order, but with the same look !

**Comment by IAmTamal** [comment]
Is it ready to be merged ?

**Comment by 4k5h1t** [comment]
Nope, close. By tomorrow night most likely

**Comment by 4k5h1t** [comment]
Pretty much done, just the footer's Join Us and Report Headers

**Comment by 4k5h1t** [comment]
Hey, those two headers keep getting overridden by bootstrap.min.css _reboot.scss, I've tried almost everything to get past it, !important, inlines, etc. doesn't work yet, hence the delay

**Comment by 4k5h1t** [comment]
Made a kinda janky fix for it, just check the last commit.

**Review by IAmTamal — APPROVED** [review]
### Looks perfect !

- **Thankyou for working on the issue**
- **Do star the repo, it really helps our team, also we'll be participating in hacktoberfest !**
- **Keep contributing to Opensource 💚**

**Pull request merged**
