### PR TITLE
fix: adds explicit width and height to images

### PR DESCRIPTION
**Pull request by vikaskumar2703**
## Related Issue 

Closes: #634

#### Describe the changes you've made ✍
Set an explicit width and height on images elements to reduce layout shifts and improve CLS.

### CODE REVIEW

**Review by IAmTamal — APPROVED** [review]
**Amazing work,**
This looks good to me, will be merged soon 🎉. 

Also, @priyankarpal, do you want to add something ?

**Review by priyankarpal — CHANGES_REQUESTED** [review]
Please add alt texts

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Hi @vikaskumar2703  

A great approach to use Alt texts, but since alt texts are read by screen readers, it would be good to write actual texts, instead just of random text.

For example, you can generate such Alt texts using [Alt Text Generators](https://alttext.in/), just download the image, and put it there. You can then use such alt texts and replace the current random alt texts with these.

image

**Comment by priyankarpal** [comment]
@IAmTamal this is an amazing website 😲  I didn't know that. Thank you for sharing it with us.

**Comment by vikaskumar2703** [comment]
@IAmTamal i had no idea about Alt text generators and what exactly has to be written in Alt text . Now i get their point and would commit the changes asap

**Comment by IAmTamal** [comment]
> @IAmTamal this is an amazing website 😲 I didn't know that. Thank you for sharing it with us.
> 
> btw is this website open source?

A person named Aditya Oberai made it, I think it is OSS. 
Here's the [Repository](https://github.com/adityaoberai/Alt-Text-Generator), and here's the [Tweet](https://twitter.com/adityaoberai1/status/1652314836787937281)

**Review by IAmTamal — APPROVED** [review]
**Amazing work,**
This looks good to me, will be merged soon 🎉.

**Pull request merged**
