### PR TITLE
added footer

### LINKED ISSUE #576: [FEATURE] Footer
### Description

how about adding a footer to the website with the application name and the same links that are in the navbar.

### Screenshots

_No response_

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by rohinish404**
# Fixes Issue #576 

**My PR closes #576 **

# Changes proposed

## What were you told to do ?
To add the footer.

## What did you do ?
Did the same.

---

# Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
Screenshot 2023-01-29 at 1 02 18 PM

# Screenshots

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Hi @rohinish404 The footer already looks good, however i'd suggest some changes to be made !

### Changes : 
image

- Can we make the headings bold and have them the `font-family: Montserrat,sans-serif` ? 
- Also the normal texts should have `poppins` as their font family.
- Instead of just `Milan` we should write `Developed by team Milan © 2023`
- Instead of `We are an Opensource product,
feel free to contribute here` maybe we can write `Want to join Team Milan ? Contribute here !`

**Comment by rohinish404** [comment]
i've made the changes..should i also add font-family: Montserrat,sans-serif to the want to join team milan heading??

**Comment by IAmTamal** [comment]
> i've made the changes..should i also add font-family: Montserrat,sans-serif to the want to join team milan heading??

I think that will look good

**Comment by rohinish404** [comment]
> > i've made the changes..should i also add font-family: Montserrat,sans-serif to the want to join team milan heading??
> 
> I think that will look good

ohk..i'll add the font.

**Comment by rohinish404** [comment]
So im getting an error while pushing the changes and i don't know how to resolve that.

**Comment by IAmTamal** [comment]
> So im getting an error while pushing the changes and i don't know how to resolve that.

What's the error you get ?

**Comment by rohinish404** [comment]
This is the error
Screenshot 2023-02-01 at 11 11 48 PM

**Comment by rohinish404** [comment]
It's asking for a branch..which one should i write??
rohinish-patch-2 or main?

**Comment by rohinish404** [comment]
> It's asking for a branch..which one should i write?? rohinish-patch-2 or main?

rohinish-patch-1*

**Comment by rohinish404** [comment]
So i think this is looking good, the only thing left is to add the font family to the left side text only. Maybe that can be added after merging of this because i don't know what other things have i done with pushing and pulling.🥲
What do you think?

**Comment by IAmTamal** [comment]
See you are currently on the [rohinish-patch-1](https://github.com/rohinish404/Milan/tree/rohinish-patch-1) branch. So if you want more changes just `git checkout [rohinish-patch-1](https://github.com/rohinish404/Milan/tree/rohinish-patch-1)` and after that make your changes, then commit, and push it.

**Comment by rohinish404** [comment]
Finally done with this thing. Solved the error i was facing. Thanks for the help :)

**Review by IAmTamal — CHANGES_REQUESTED** [review]
The content LGTM ✅
**However i think the responsiveness is broken :** 

image

image

**Comment by rohinish404** [comment]
Is this looking good?
Screenshot 2023-02-06 at 2 56 34 PM

**Comment by IAmTamal** [comment]
@rohinish404  Alot has improved, however there are some small changes that can come in handy !

For example we can have this centered in such conditions maybe 
image

Also a gap would be beautiful after the `report` button: 

image

**Comment by rohinish404** [comment]
I was thinking instead of making it centered how about we make it look like this👇
Screenshot 2023-02-08 at 1 12 04 AM

**Review by IAmTamal — APPROVED** [review]
LGTM ✅

**Comment by rohinish404** [comment]
Are there any other changes needed?

**Pull request merged**
