### PR TITLE
Accessibility : Highlighting errors in contact form 

### LINKED ISSUE #329: Accessibility : Highlighting errors in contact form
### Description

- [x] I have read the contributors guidelines .
- [x] I have read the code of conduct.
<hr>
In the contact us page, the toastify notification just mentions "Resolve Errors in the Form", but it doesn't highlight what are the errors in the form.  It would be helpful to the user if we can notify what are the errors in the form.
My approach to the problem:
* We can highlight the form entries which have incorrect type of information along with a single toastify notification.

### Screenshots

Screenshot 2022-10-01 144438

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MANUSRAO**
* Accessibility : Highlighting errors in contact form  (#329)
# Issue  📐

- **I @MANUSRAO have worked for #329**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #329**

## Screenshots 📷

**Here are the pictures of changes that I have made 🔽**

---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
## Some changes i'd suggest  :

- Hello there, the first condition is working perfectly, good job ✅
- The email verification however is not working as you can see in the screenshot below
- I just tested it out with the email as `gyasdasdas asdas` , yet the value went to my DB instead of error

image

## Note : 
- Do work on the changes and make sure to tag me once done !

**Comment by MANUSRAO** [comment]
We will make the necessary changes and tag you.

**Comment by MANUSRAO** [comment]
Hi @IAmTamal ! I tried replicating your output and noticed something. If you enter all correct details and submit a form, and within next 10 seconds if you enter wrong details the form still accepts it !! So I tried changing regex rules, but still the error exists! Can you check if the same happens to you? If yes, then this might be a bigger problem.

**Comment by IAmTamal** [comment]
> 

Hmm i see, can we like disable the button perhaps until and unless there's a valid email ? 
Like i donot want to send something to DB with a broken mail

**Comment by MANUSRAO** [comment]
I think I found the main problem, whenever we get a correct email we set `isEmailValid` as true. But since we do not reset its value for next form entry it still remains true. So any next entry if it has wrong email is accepted. So, my solution is we can ditch useState component for checking email and verify it only when user press submit OR we can use our `onChange` handler to set `isEmailValid` false for wrong inputs rather than setting only `true`. Please tell me which approach should I use?
I can make PR today itself.

**Comment by MANUSRAO** [comment]
Also, the present email evaluator has wrong regex evaluator.  It used to allow emails like `abc..def@mail.com` and many such invalid emails. That's why I have created a new function to verify such errors and accept only correct emails.

**Comment by MANUSRAO** [comment]
Hi @IAmTamal I think this fixes all the validation issues. Can you please verify or any other changes need to be made?

**Pull request merged**
