### PR TITLE
feat: password visibility toggle button added

### PR DESCRIPTION
**Pull request by SINJINI-G**
## Related Issue 
Closes: #716 

## Changes made 👷🏻‍♂️
- toggle button added
- UserRegister.jsx and UserLogin.css updated

### CODE REVIEW

**Comment by SINJINI-G** [comment]
Hey @IAmTamal !! Can you review my PR and merge it?

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Hi there, please watch [this](https://www.loom.com/share/46a77b9c664e4deb917887f70ecdfd18), with VOLUME TURNED ON.
The changes will be clear.

**Comment by SINJINI-G** [comment]
> Hi there, please watch [this](https://www.loom.com/share/46a77b9c664e4deb917887f70ecdfd18), with VOLUME TURNED ON. The changes will be clear.

Hi! I have seen your video and noted down the changes you want.. I will start working on it and keep you updated.. thank you for the review..

This issue (#716) has a level 2 tag on it.. can you change it to level 3 please? Thanks again!

**Comment by SINJINI-G** [comment]
> Hi there, please watch [this](https://www.loom.com/share/46a77b9c664e4deb917887f70ecdfd18), with VOLUME TURNED ON. The changes will be clear.

Hii @IAmTamal! I have made the changes that you asked for. Kindly review the PR.

**Review by IAmTamal — APPROVED** [review]
**Amazing work,**
This looks good to me, will be merged soon 🎉.

**Pull request merged**
