### PR TITLE
fix: add placeholder text to input forms

### LINKED ISSUE #269: Club Registration + Login Page
### Description

# The club registration + Login  page has bugs
 - When you take a look at `Image1`, you will notice that we donot have placeholder for the form in mobile
 - Make sure there are appropriate placeholders **only** for the mobile ! 
 - Make sure the **marked part** in `Image 2 ` is side by side for the mobiles too ! 

### Screenshots

# Image 1

image

# Image 2

image

### Additional information

Link : https://milaan.vercel.app/clubs/register
Link : https://milaan.vercel.app/clubs/login

### PR DESCRIPTION
**Pull request by Dun-sin**
# Issue  📐

- **I Dunsin have worked for #269 **

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #269 **

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**
image
image

  
  
  
---

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
### Placeholders look good

 - The placeholders looks perfect, but i would request a minor change to Club registration.
 - If you take a look at `Image 1` , the **password** and **confirm password** are vertical
 - I think it would look much better if it was horizontal for mobile devices ! 
 
 
### Image 1
image

**Comment by Dun-sin** [comment]
> ### Placeholders look good
> 
>     * The placeholders looks perfect, but i would request a minor change to Club registration.
> 
>     * If you take a look at `Image 1` , the **password** and **confirm password** are vertical
> 
>     * I think it would look much better if it was horizontal for mobile devices !
> 
> 
> ### Image 1
> 
> image

Sure, i will see what i can do

**Review by Dun-sin — COMMENTED** [review]
Fixed the password input field alignment

**Review by IAmTamal — APPROVED** [review]
Looks perfect, thanks for your work @Dun-sin  ! 
Keep contributing to Opensource.

**Pull request merged**
