### PR TITLE
[BUG FIX] Fixed the alignment of the social-btn

### LINKED ISSUE #398: Misalignment of Social Icons
### Description

- On inspecting the CSS of `social-btn` I found that icons are being tried to keep at the center by using some hardcoded values
-  This would lead to an issue when clients with different screen dimensions may get to see the misaligned icons

### Screenshots

The above problem I mentioned, occurred with my system
>misalignment-social-icons

### Additional information

Instead of simply hardcoding the positional values, one can use the power of creating it into `flex`

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by arpitv970**
# Fixes Issue

**My PR closes #398**

# Changes proposed

## What were you told to do ?

- Fix the alignment of social icons
- Reduce the dependency on hardcoded positional values

## What did you do ?

- [x] Fixed above-mentioned problems using `flex` & other properties _(justify-content, align-item, etc.)_
- [x] Also enhanced the CSS around it
---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

Here are the visible results of the fix
> fix-misalignment-social-icons

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
All the other button looks fine when hovered except the contact button
image

**Comment by arpitv970** [comment]
Now I have removed the hardcoded values for the `cont-icon`
> fix-misalignment-social-icons-2

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
