### PR TITLE
#191  Fix :  how the Contact Page looks 

### LINKED ISSUE #191: Contact Page looks bad
### If you take a look properly the contact form looks bad on the right hand side with that square thing and black drop shadow I want you to design a minimal impressive design for the contact page and also make it responsive enough for mobiles and tablets.

**ALSO** try and change the picture to more high quality SVG from Storyset if possible.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Hat52**
# Contact Page looks bad 📐

- **I HAT52 have worked for 191 under JWOC**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #191**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
image

image

  
image

  
---

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
## I need major design changes 🛠

If you have not noticed i did mention in the issue about the **dropshadow** as wel as a **minimal** design. 

Try refering : **[Dribble Design 1](https://dribbble.com/shots/18559477-Contact-form-Mattered)**
Or : **[Dribble Design 2](https://dribbble.com/shots/14126196-Contact-Form-01)**

**Comment by hamzaSCM** [comment]
Do we need to add any extra field like the the dribble designs that you have mentioned?

**Comment by Hat52** [comment]
Do we need to add extra fields that are present in the design or stick with the ones that we have in our form?

**Comment by IAmTamal** [comment]
> Do we need to add extra fields that are present in the design or stick with the ones that we have in our form?

You can stick to the one that we have in our current form , 
I encourage changing the design !!

**Comment by Hat52** [comment]
image
image
image

**Comment by IAmTamal** [comment]
Hmm the basic design seems ready , i will make other issues for more styles !! 
I will merge it for now , great work @Hat52

**Comment by Hat52** [comment]
Great 👍

**Pull request merged**
