### PR TITLE
docs: updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Shalini469717**
## Related Issue 

Closes: #653 

#### Describe the changes you've made ✍
Fixed the typo

### CODE REVIEW

**Comment by IAmTamal** [comment]
Hi @Shalini469717, please fix your Pull request title, we have talked about it in the [Pull request section](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-) of the Contributing Guidelines.

**Comment by Shalini469717** [comment]
Fixed it. Maybe we can mention that the title should start with a lowercase letter as well in [the Lint](https://youtube.com/shorts/SOfrn7NefBM?feature=share). I changed the title again once I got the error.

**Comment by IAmTamal** [comment]
> Fixed it. Maybe we can mention that the title should start with a lowercase letter as well in [the Lint](https://youtube.com/shorts/SOfrn7NefBM?feature=share). I changed the title again once I got the error.

Well that is the reason we have put in our docs, and all the first time contributors are specially expected to go through the docs.

**Review by IAmTamal — APPROVED** [review]
**Amazing work,**
This looks good to me, will be merged soon 🎉.

**Comment by Shalini469717** [comment]
> **Amazing work,** This looks good to me, will be merged soon 🎉.

Thank you for the help

**Pull request merged**
