### PR TITLE
style: updated footer layout and style

### PR DESCRIPTION
**Pull request by rupali-codes**
## Related Issue 

Closes: #623 

#### Describe the changes you've made ✍
* Fixed Milan logo
* Changed the background color
* Added new component for _socials_ 
* Removed _socials_ links from the bottom
* And it's responsive!

#### Screenshots (if any) 📸

Before 

image

Now
image

### CODE REVIEW

**Comment by rupali-codes** [comment]
@IAmTamal any changes required?

**Comment by IAmTamal** [comment]
> @IAmTamal any changes required?

There are a few conflicts, would be great if you could resolve and tag me in !

**Comment by rupali-codes** [comment]
@IAmTamal I have resolved the conflicts :)

**Review by IAmTamal — APPROVED** [review]
**Amazing work,**
This looks good to me, will be merged soon 🎉.

**Pull request merged**
