### PR TITLE
Designed HomeCardsContainer component for Home page

### PR DESCRIPTION
**Pull request by mridul4101**
This is a new feature for issue #49.

Closes: #49

**Updates -**
- `/milan-app/src/components/HomeCardsContainer.jsx` : Designed home page according to [Figma Design](https://www.figma.com/file/sPVLhYppzhCzYYbqSmlebm/Untitled?node-id=0%3A1)
- `/milan-app/src/styles/HomeCardsContainer.css` : Added styling for the above

**Additions -**
- Added aos package

Added these images for home-page:
- `/milan-app/src/assets/pictures/bg-bottom.png`
- `/milan-app/src/assets/pictures/connect.png`
- `/milan-app/src/assets/pictures/hand.png`
- `/milan-app/src/assets/pictures/serve.png`

**Screenshots -**
Screenshot (58)
Screenshot (56)

### CODE REVIEW

**Comment by IAmTamal** [comment]
@mridul4101  

I see **wrong images**. Also i just need 2 cards ( according to Figma design) 
image


**Please fix the font size, color, family. It's all written in the Figma design**
image



---

### This is just what i need. 
image

**Review by IAmTamal — CHANGES_REQUESTED** [review]
- [x] commented.

**Comment by mridul4101** [comment]
Okay...will be done

**Comment by IAmTamal** [comment]
> Okay...will be done I actually started with the previous web version, I'll correct it by morning.

NP , lots of time.

**Review by IAmTamal — APPROVED** [review]

**Pull request merged**
