### PR TITLE
fix: ui for report modal

### LINKED ISSUE #610: [BUGS] Report modal makes site look bad
### Description

- If you open the report modal on desktop, you'll see how the navbar has glitched out
- Plus for the buttons inside the report modal we are not using our theme color `#e26959` for buttons

### Screenshots

image

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

### PR DESCRIPTION
**Pull request by vatsalsinghkv**
# Fixes Issue

Closes #610 

# Changes proposed

- Feat: to close the report modal whenever clicked on the overlay (translucent background)
- Fixes Placeholders in the report modal (not working)

## What were you told to do ?

- To fix the **navbar**  when report modal is opened
- To change **report modal button** colour to `#e26959`

## What did you do ?

- Changed the `z-index` values of **navbar** and **report modal** as `10` & `20` respectively
- Added bootstrap default `.btn` styles and added the `#e26959` as background
- Prettier formatted the code of the changed file
---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

**Before:**
Screenshot 2023-03-21 at 11 02 02 PM

**After:**
Screenshot 2023-03-21 at 10 59 00 PM

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Looks better, but for some reason the placeholders are too black. We can maybe improve the placeholders. 

They can be `grey` instead of  black i guess. Because it's looking more bold. Placeholders shouldn't stand out so much.

**Comment by vatsalsinghkv** [comment]
> Looks better, but for some reason the placeholders are too black. We can maybe improve the placeholders.
> 
> They can be `grey` instead of black i guess. Because it's looking more bold. Placeholders shouldn't stand out so much.

Fair enough, do we have recommended colour palette or should I pick a slate colour from [tailwindcss colours](https://tailwindcss.com/docs/customizing-colors)?

**Comment by vatsalsinghkv** [comment]
@IAmTamal what do you think about this colour for placeholders?

Screenshot 2023-03-27 at 9 27 02 PM

**Comment by vatsalsinghkv** [comment]
@IAmTamal would like to add this functionality where report modal closes on touching the backdrop.

**Comment by vatsalsinghkv** [comment]
@IAmTamal Whenever we open the modal we got that translucent black background, so I am suggesting this feature that whenever we click that black background our modal closes. It's good user experience we users won't have to rely on that tiny cross button only.

Like this: 

https://user-images.githubusercontent.com/68834718/228320697-5b051462-82eb-45ab-92bf-4148c604bc44.mov

**Comment by IAmTamal** [comment]
@vatsalsinghkv 

 - I am not a fan of the first suggestion, the reason is what if the user closes by mistake. It hapened with me couple of times and in most of the cases all popups would close just by that button. So i'd recommend to not implement it.

 - The second option sounds amazing, you can perhaps make a new issue. We'll merge this and work on that !

**Pull request merged**
