### PR TITLE
Welcome Page Fix ! 

### LINKED ISSUE #224: Welcome page fix 🛠
### Description

When you login as an **User** in our site, it takes you to **Welcome Page**
As you can see the welcome page is not full screen in the **screenshot**

---

- I need to make it so that it is fullscreen for desktop
- Make sure it looks on Mobile and doesnot breaks ! 

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rohitroy-github**
# Issue  📐

- **I Rohit Roy have worked for #224**

[X]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #224**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

image
  

  
---

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
For some reason the Welcome page still looks the same for my deploy preview by the bots. 

Can you please record the screen ( you can use OBS ) , and show that after Logging in as user, the  welcome screen is full even when you zoom in and out !

**Comment by rohitroy-github** [comment]
Okay, so when we are zooming in or out then it's changing but in 100% screen size it fits perfectly.

**Comment by rohitroy-github** [comment]
Here are the screenshots from the bot-deployed site 
That's in 25% screen size > 

image

That's in 100% screen size > 

image

**Comment by rohitroy-github** [comment]
Cool, I'm looking into it.

**Pull request closed without merging**
