### PR TITLE
Updated Toast

### LINKED ISSUE #378: Some Minor changes in 'LoggedIn' Toast.
### Description

Here are few changes that I think can be made : 

- First of all the time it takes to log in is a bit more, which can be reduced by few milliseconds.
- Instead of 'Logged In' , It should show 'Logging In'.
- There is a feature that is just by clicking on that toast we are able to LogIn , that should be removed and so the user should wait untill the bar ends  which makes it more Authentic.

### Screenshots

Toast at Top-Right : 

toast

Hey @IAmTamal  Please review it , I would love to Fix it.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DhruvRathi2001**
# Fixes Issue

 Closes #378  

My PR closes #378 

# Changes proposed

## What were you told to do ?
I was told to modify toast ,add some feature and remove some feature from it.

## What did you do ?

I made necessary changes in toast in every file it was being used.

---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

toast_final

Hey @IAmTamal  I made the changes you mentioned , have a look.

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hmm it'll be okay. 
**Please fill up the PR details** - i will merge the PR after it :)

- Rest all looks good

**Comment by DhruvRathi2001** [comment]
@IAmTamal  Can u tell me please like how to update existing PR like here only, without creating a totally new PR.
Because if i make new PR i have to close this one

**Comment by IAmTamal** [comment]
@DhruvRathi2001 

You can go to your forked version, and update the fork.

image


Once this is done, your forked version will be updated.
Now open your fork version with code.  

This depends on you, i use GitHub desktop so it's simple for me : 
image

Next, just in the terminal do `git pull origin main` (if you are not using GitHub desktop)
And write your code and simply push the code. 

Any change to the code you make to your forked version (without creating a new branch) will be reflected here !

**Comment by DhruvRathi2001** [comment]
OK ,Thanks a lot.

**Pull request closed without merging**
