### PR TITLE
fix: Events page mobile #382

### LINKED ISSUE #382: Bug : Events page mobile
### Changes recommended : 

The events page when looked in mobiles has a lot of unused space. 
The contents are crammed up vertically, more likely that the div/anything has a padding/margin which is why it is like this.

- Can you make it so that almost the full screen is covered without so much space to the side ? 

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iakgoog**
# Issue  📐

- **I , Sutthinart Khunvadhana, have worked for #382**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #382**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

Screen Shot 2565-10-06 at 07 09 40
Screen Shot 2565-10-06 at 07 09 54
Screen Shot 2565-10-06 at 07 10 05

  
  
  
---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Always get the issue assigned first before making a PR :)

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Comment by iakgoog** [comment]
> Always get the issue assigned first before making a PR :)

Acknowledge and will follow the open source community convention

**Pull request merged**
