### PR TITLE
Fix:Updated navlinks, Now changes color on hover

### LINKED ISSUE #322: Navlinks doesn't change on mouse hover
### Description

A slight colour in change on hovering the nav links would make it more appealing and attractive.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imyoungsparda**
# Issue  📐

- **I Ayush Raj have worked for #322 **

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #322 **

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
  
image

  
---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
The Hover functionality looks good, but instead of gray can we have `#297f75` instead ?

**Comment by imyoungsparda** [comment]
Yes sir, Sure.

Let me do this

**Review by IAmTamal — APPROVED** [review]
### Looks perfect !

- **Thankyou for working on the issue**
- **Do star the repo, it really helps our team, also we'll be participating in hacktoberfest !**
- **Keep contributing to Opensource 💚**

**Comment by imyoungsparda** [comment]
It was nice working on this project. Will keep contributing to this wonderful project. 
Thank You so Much @IAmTamal

**Pull request merged**
