### PR TITLE
refactor: refactor the button and tagline component in clubdetails.css 

### PR DESCRIPTION
**Pull request by ayushmangarg2003**
## Related Issue 

Closes: #605

#### Describe the changes you've made ✍
I have changed the design of the button so that is matches rest of the website and reduced the font size of club tagline as I think that it would look better if it is smaller. Also added hover effect to the button.

#### Screenshots (if any) 📸
This is how it looked earlier.

Screenshot (2)

### CODE REVIEW

**Comment by IAmTamal** [comment]
@ayushmangarg2003 Please rename your PR according to the comments above !

**Comment by ayushmangarg2003** [comment]
Done

**Comment by IAmTamal** [comment]
> Done

Hi there, you need to add the PR title as suggested by the bot example : `fix: A bug fix` , or `feat: bla bla bla`

Chexk other PRs.

**Comment by ayushmangarg2003** [comment]
Sorry for that, actually I am not very familiar to Open-Source, but now I think title is good.

**Review by IAmTamal — APPROVED** [review]

**Pull request merged**
