### PR TITLE
add a banner for clubs - #253

### LINKED ISSUE #253: 🚀 Add a banner for clubs !
### We need a banner

If you look at the **Donate Us** page, you will see a banner --> `Image 1`
But the **Clubs** page has none.  --> `Image 2`

**Donate Us Page** : https://milaan.vercel.app/donateus
**Clubs Page** :  https://milaan.vercel.app/display/clubs

Can we have a banner where the clubs page has a similar one too ? 
You can use a good image from internet. 

**Heading**

Clubs and communities ! 

**Sub-heading**

Here are some clubs you can follow, you can attend club events and even get notified about it once you subscribe !

## Image 1 

image

## Image 2 

image

### Additional information

The Design is upto your skills. 

**Image resources :** 

 - https://undraw.co/illustrations
 - https://storyset.com/

### PR DESCRIPTION
**Pull request by roei111**
# Issue  📐

- **I Roei, have worked for #253 **

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #253**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

milan-clubs-desktop
milan-clubs-mobile
  
  
  
---

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
## Some small changes i would love to have. 

image

Here's something i recommed : 
 - The Banner can be a bit smaller
 
**Take a look at this :**
image

**Comment by roei111** [comment]
Hey, @IAmTamal I made the changes, can you review them?

**Comment by IAmTamal** [comment]
Can you resolve the conflicts please ?

**Review by IAmTamal — APPROVED** [review]
Looks good to me ✅

**Pull request merged**
