### PR TITLE
This is resolved PR made for issue #370

### LINKED ISSUE #370: Registration page , name input accepts empty spaces (" ")
### Description

The registration page is accepting empty spaces as input, and logging us in with empty name, address etc.

### Screenshots

image

### Additional information

I would like to work on this issue, please assign this to me

### PR DESCRIPTION
**Pull request by AdarshBajpai67**
# Fixes Issue

My PR closes #370

# Changes proposed

## What were you told to do ?

If any field is empty and you click on register the toast should say "Please fill all the fields"

## What did you do ?

Fix: spaces and numbers in name input field not allowed
# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots
Numbers are not allowed in name

image

image

spaces not allowed in address and pincode

image

image

spaces input in club registration fixed

Screenshot (2)

Screenshot (3)

Screenshot (4)
Screenshot (6)
Screenshot (7)

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image


## Bug description : 

- I filled the empty pincode it showed us `Please fill all fields` that is **okay !**
- Then i filled the pincode and then clicked the button, yet it says `please fill all fields`

**Comment by AdarshBajpai67** [comment]
can you please share the full screenshot.

**Comment by IAmTamal** [comment]
> can you please share the full screenshot.

Fix this.

https://user-images.githubusercontent.com/72851613/195516277-921b9c00-f7af-48e3-9d8c-8575692b55bb.mp4

**Comment by AdarshBajpai67** [comment]
hey Tamal,

Can you describe the characters that we input in the club name field, as i
have disabled special characters in name.

**Comment by IAmTamal** [comment]
> Can you describe the characters that we input in the club name field, as i have disabled special characters in name.

Anything can be the name of the club. We can though exclude specials characters except for hyphen

**Comment by IAmTamal** [comment]
@AdarshBajpai67 It has been 7 days, if there is no response from your side i will be closing the PR.

**Pull request closed without merging**
