### PR TITLE
style: changed looks of user register page

### PR DESCRIPTION
**Pull request by Deva-1903**
Closes: #625 

#### Screenshots (if any) 📸
Screenshot (309)

### CODE REVIEW

**Comment by IAmTamal** [comment]
@Deva-1903 Please fix the name of the PR as suggested by the bot.

**Comment by Deva-1903** [comment]
> @Deva-1903 Please fix the name of the PR as suggested by the bot.

Done

**Review by IAmTamal — CHANGES_REQUESTED** [review]
The changes look good to me, however, can we do the same for the User Login page? 
We have some unused emojis there which can be removed.

**Comment by Deva-1903** [comment]
> The changes look good to me, however, can we do the same for the User Login page? We have some unused emojis there which can be removed.

Done.👍

**Review by IAmTamal — APPROVED** [review]
**Amazing work,**
This looks good to me, will be merged soon 🎉.

**Pull request merged**
