### PR TITLE
[FIX] : Made detailed club page responsive

### LINKED ISSUE #594: [FEATURE] Upgrading the look of detailed club page
### Description

- Add the `tagline` instead of adress in the clubs card
- Make the detailed clubs page more attractive, try using your FE skills and giving this page the best look you can think of !
- Make the detailed club page mobile responsive as well (for all devices)

### Screenshots

https://user-images.githubusercontent.com/72851613/217578497-4e0bdcaa-b1b8-456a-961e-99dca35712aa.mp4

image

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

### PR DESCRIPTION
**Pull request by Satyam005**
# Fixes Issue

Closes #594 

## Changes proposed
-  To made the page responsive can use bootstrap grid system along with media queries

## What were you told to do ?
- To add tagline in place of address in clubs card
- To make the detailed club page mobile responsive as well (for all devices)

## What did you do ?
- Replaced address with tagline in clubs card
- Used bootstrap grid system along with media queries to make the detailed club page responsive for mobile, tab, and bigger screens

---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots
- Mobile View
(Before change)
image
(After change)
218328480-7025a649-5cd3-4cd9-afce-ad68e4bb285a

### CODE REVIEW

**Comment by IAmTamal** [comment]
Hi @Satyam005 this looks good - sorry about being late, have been super busy IRL. There's test crashing, but donot worry, i will fix those ASAP and get back to you.

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image

- As you can see the image as well as the header looks too big. The image can be of less size. It looks gigantic.
- Maybe also we can replace the 📌 icon with a location icon
- We can also get rid of the `#f2f2f2` background, honestly it doesnot looks clean.
-  Also we can have another section below these called `Events by this club` , (centered header) where we will be showcasing the events hosted by this club.
- The `Welcome to` in the header can be black, and the club name only in `#e26959`
- Also increase a gap between the footer and the stuffs in the page.

**Comment by Satyam005** [comment]
sure @IAmTamal  will make the requested changes

**Comment by Satyam005** [comment]
@IAmTamal  can i get the data obj for the section `Events by this club` . Want to know what's the data that will get displayed here

**Comment by IAmTamal** [comment]
@Satyam005 , for now we can say have like 3 `demo events card` consisting of totally `random data` which represents the fact that hey, this  particular Club has hosted these 3 events till date.

The design for the events card can be the same as the cards in [Events page](https://milaan.vercel.app/events)

**Comment by IAmTamal** [comment]
Are you working on it @Satyam005 , if not i'd like to assign someone else !

**Comment by Satyam005** [comment]
> Are you working on it @Satyam005 , if not i'd like to assign someone else !

hi @IAmTamal, sorry I was busy for the past couple of weeks. I'll raise a PR in 1-2 days if that's okay with you

**Comment by Satyam005** [comment]
Hi @IAmTamal , made the requested changes, will still need some clarity on the `Events by this club` like where it should be placed

**Review by IAmTamal — APPROVED** [review]
**Amazing work,**
This looks good to me, will be merged soon 🎉. 

The rest of the work, such as `Events by this club` can be done later, once i clearly make an issue. So that it will be easier to understand.

**Comment by Satyam005** [comment]
Thanks @IAmTamal, looking forward to contributing more...cheers

**Pull request merged**
