### PR TITLE
fix: address and pincode now do not accept only spaces as input

### LINKED ISSUE #370: Registration page , name input accepts empty spaces (" ")
### Description

The registration page is accepting empty spaces as input, and logging us in with empty name, address etc.

### Screenshots

image

### Additional information

I would like to work on this issue, please assign this to me

### PR DESCRIPTION
**Pull request by AdarshBajpai67**
# Fixes Issue

My PR closes #370

# Changes proposed

## What were you told to do ?

If any field is empty and you click on register the toast should say "Please fill all the fields"

## What did you do ?

Fix: spaces and numbers in name input field not allowed
# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots
Numbers are not allowed in name

image

image

spaces not allowed in address and pincode
image

image

### CODE REVIEW

**Comment by AdarshBajpai67** [comment]
hey @IAmTamal, i have made the pr and solved address and pincode issue, please review it, 

thanks 👍

**Comment by AdarshBajpai67** [comment]
and please consider adding hacktoberfest to the repo.

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image

Are you sure your changes are working ? 
Like i put 4-5 spaces and still got registered

**Comment by IAmTamal** [comment]
> image
> 
> Are you sure your changes are working ? Like i put 4-5 spaces and still got registered


image

I don't see any checks for Pincode, Adress and so on. All changes you made are for First and last name.

**Comment by AdarshBajpai67** [comment]
i have worked on user registeration page,

for club registeration i will raise a pr separately

**Comment by IAmTamal** [comment]
You can make a same PR itself, we would have less PRs and mess that way .

**Pull request closed without merging**
