### PR TITLE
Club and User Login Form UI Improvements, Better Transition

### LINKED ISSUE #420: [OTHER] Club and User Login Page Form UI Improvements
### What would you like to share?

# Club and User Login Page

1. inconsistent on Mobile and large screen view. 
2. Unnecessary Centering of elements. 
3. Login Button Size Reduction 
4. Remember Me Label Font Family
5. Left and Right Padding in Form element in the Mobile View

I have done some changes in the code so that these issues are resolved. I am opening a PR.

### Additional information

image
Looks Congested

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by stereogon**
# Fixes Issue

**My PR closes #420 **

# Changes proposed

## What did you do ?

1. Removed Unnecessary Centering of Elements in the Mobile View, giving the app a consistent styling.
2. Changed Login button Size for Smoother looking transition.
3. Added left and right padding to the form element for cleaner UI.
4. Made Remember Me check box visible in the Mobile view as well.
---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

image

### CODE REVIEW

**Comment by IAmTamal** [comment]
@stereogon  - NEVER create a PR until and unless you are assigned to that issue.

**Review by IAmTamal — CHANGES_REQUESTED** [review]
Some changes needs to be done  : 

image

- Make sure these are centered
- The padding looks better.
- Center the login button !
- Keep the remember me as it is !

**Comment by stereogon** [comment]
Sorry for opening the pull request without being assigned to the issue. I have made the Requested Changes.

**Comment by stereogon** [comment]
Sorry for opening a Pull Request without being assigned to the issue. I have made the requested changes.

**Comment by IAmTamal** [comment]
image

Make these centered !

**Comment by stereogon** [comment]
I have already made this change, please check the latest commit.

**Comment by stereogon** [comment]
I have Resolved the conflicts.

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
