### PR TITLE
implemented changes to fix card size

### LINKED ISSUE #446: Design of a card in the events page is different from others.
### Description

Design for third card or "Hello" event is different and it also contains some random words.

### Screenshots

image

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nihshesh**
**My PR closes #446**

# Changes proposed

## What were you told to do ?

Fix the difference in card sizes issue.

## What did you do ?

Implemented changes to fix the card size by changing min height property.

---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

image

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image

This is how the size difference is looking. Please fix this

**Comment by IAmTamal** [comment]
Do let me know if you think all the changes are made 

( include screenshots )

**Comment by IAmTamal** [comment]
> This screeenshot is without any new changes. Is this not correct? image

image
 Here's the height difference.

**Comment by nihshesh** [comment]
But in my local it is fine only. No Problem you can close this PR and assign it to someone else. 
Thanks.

**Comment by IAmTamal** [comment]
> But in my local it is fine only. No Problem you can close this PR and assign it to someone else. Thanks.

That's why i asked you to check  the deployment preview 
The screenshot you sawe, is from the same.

**Pull request closed without merging**
