### PR TITLE
Fix : Anchor tags 🛠

### LINKED ISSUE #211: Footer login and register anchor tags works locally but not when deployed.
### Description

The login and register links on the footer of landing page is not working and throwing a 404 error when clicked.

### Screenshots

Screenshot from 2022-07-09 11-28-27
Screenshot from 2022-07-09 11-28-35

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adithgit**
# Issue  📐

- **I Adithya Udayan have worked for #211**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #211 **

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

  
Screenshot from 2022-07-09 11-50-58

---

### CODE REVIEW

**Review by IAmTamal — APPROVED** [review]
Great work  ✅

**Review by IAmTamal — CHANGES_REQUESTED** [review]
It'll be great if you handle the conflicts !

**Comment by adithgit** [comment]
I've resolved the conflicts.

**Review by IAmTamal — APPROVED** [review]
✅

**Pull request merged**
