### PR TITLE
Bug:improved labels,placeholder update user page

### LINKED ISSUE #380: bug: labels and placeholder missing in update user page
### Description

The update user page is bland. User can't understand what they are actually updating. I don't know update profile feature works or not. But I can work on it. And apply relevant labels to inputs

### Screenshots

Screenshot_2022-10-05-22-16-58-245_com android chrome

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tanishk-23**
# Fixes Issue
My PR Closes #380

# Changes proposed

## What were you told to do ?
I was told to add labels and placeholders which were missing in update user page on small screen devices.

## What did you do ?
I added placeholders which were missing in update user page and also changed display property of labels to font-size: large
---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots
Mobile View
MobileView

Desktop View
DesktopView

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
- Make it conditional such that placeholders are seen only for mobiles

Example :  https://milaan.vercel.app/user/login
image

**Comment by tanishk-23** [comment]
@IAmTamal I have done the suggested changes. Please review and let me know if i can make PR.

screencapture-localhost-3000-user-profile-2022-10-10-21_07_08

**Comment by IAmTamal** [comment]
@tanishk-23 Push the changes to the PR please !

**Comment by tanishk-23** [comment]
@IAmTamal I have pushed the changes to the PR.

**Comment by tanishk-23** [comment]
@IAmTamal If you are satisfied with the changes then please merge my PR and if further changes are required please let me know.

**Comment by IAmTamal** [comment]
> @IAmTamal If you are satisfied with the changes then please merge my PR and if further changes are required please let me know.

image

Placeholders **should not be visible** on desktop.

**Comment by tanishk-23** [comment]
@IAmTamal Implemented the changes.

UpdateChange

**Comment by IAmTamal** [comment]
@tanishk-23 You don't need to tag me and post SS everytime. Simply push the code to PR, we can review easily that way !

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
