### PR TITLE
Added an about page with core team and contributors section with responsive styling.

### PR DESCRIPTION
**Pull request by mridul4101**
This PR adds a new feature for issue #21.
Closes: #21 

I have tried to keep it simple and elegant and also in accordance with the theme of home page.

**Changes made -** 

- Added `/pages/about.html`
- Added `/styles/about.css`
- Added some images: 
`/images/core-team/`: place card pictures of core team members here
`/images/contributors/`: place card pictures of other contributors here
`/images/icon-pack/`: contains social media svg icons
`/images/about-bg.jpg`: about header background
`/images/dummy-profile.png`: place this as card picture for dummy cards
- Fix a typo in `index.html`: duplicate body closing tag

**Screenshots of About page:**

- screen-size > 831px

Screenshot (4)
Screenshot (5)

- screen size <= 831px

Screenshot (6)
Screenshot (12)

- Updated card

Screenshot (11)

### CODE REVIEW

**Comment by IAmTamal** [comment]
@mridul4101  I think there were some misunderstandings. 
I don't need a Border to the cards , i want the cards to have a rounded corners. 
Also , why is one card bigger than the other ? 
Can you make them the same height perhaps ?
image

**Comment by mridul4101** [comment]
@IAmTamal The cards are of the same size, I have just added that as hover effect. 
When I took the screenshot I had the cursor on the dummy card.

I'll make the corners rounded.

**Comment by mridul4101** [comment]
The zoom effect and box-shadow are hover effects.

**Comment by IAmTamal** [comment]
> The zoom effect and box-shadow are hover effects.

Keep the box shadow  , but you can remove the size hover effect 😀

**Comment by mridul4101** [comment]
Okay, pushing changes in a minute.

**Comment by mridul4101** [comment]
Done, removed size hover effect.

**Pull request merged**
