### PR TITLE
fix: updated the navbar

### PR DESCRIPTION
**Pull request by Basit46**
# Issue  📐

- **I Basit changed some code in the Navbar by using the NavLinks in the place of Links and useLocation thereby preventing more code and i also updated the css to correspond with the NavLinks**

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

###My First Contribution to Open Source
  
  
  
---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
## Hello there 

 - **Please donot make a PR without making an issue**
 - **Please donot change the template out of free will**
 - **Add screenshots, donot delete stuffs that are given in the template**

## This is how it should look

image

**Comment by IAmTamal** [comment]
@Basit46  - please make the changes as requested before 26th !

**Comment by Basit46** [comment]
Ok. Duely Noted

**Pull request closed without merging**
