### PR TITLE
fix: Update the guideline links

### LINKED ISSUE #494: The links to the Guideline Files do not work properly
### Description

The links in the `Guidelines to be followed` section in [README.md](../blob/main/README.md) do not navigate to the proper files.

### Screenshots

_No response_

### Additional information

This can be a good beginners-friendly issue.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

_No response_

### PR DESCRIPTION
**Pull request by LeGrandMAG**
# Fixes Issue

**My PR closes #494**

# Changes proposed

## What were you told to do?

I was told to fix the README.md file so that all the links in the guideline section are usable.

## What did you do?

I updated the file so that all the links work. See picture below 

---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots
image

### CODE REVIEW

**Comment by SteveSayantan** [comment]
Hello @LeGrandMAG, hope you are having a great day!! Thanks for contributing to Milan.

All the changes you have made are working fine however, it is a good practice to wrap a block element i.e. `h5` around a inline element i.e. `a` .  In that case, you need not to use `[ ](url)` format. Check the attached image for your reference.
Screenshot_20221019-123430

It would be great if you refactor your code accordingly

**Comment by LeGrandMAG** [comment]
@SteveSayantan, Thank you for the tip. Just refactored my code. Please check again and let me know if it is good to go.

**Comment by SteveSayantan** [comment]
LGTM 🎉🎉

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
