### PR TITLE
Fix Events page mobile (#326)

### LINKED ISSUE #326: Bug : Events page mobile
### Changes recommended : 

The events page when looked in mobiles has a lot of unused space. 
The contents are crammed up vertically, more likely that the div/anything has a padding/margin which is why it is like this.

- Can you make it so that almost the full screen is covered without so much space to the side ? 

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ishaanbedi**
# Issue  📐

- **I Ishaan have worked for #326 by tweaking font size for different screen sizes to make the text more readable and clean. **

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #326 **

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
  
Screenshot 2022-10-01 at 4 27 58 PM

Screenshot 2022-10-01 at 4 28 06 PM

  
---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Review by IAmTamal — CHANGES_REQUESTED** [review]
### Changes needed  :
 - The `h1` can be of `32px` instead of `24px`
 - The last line is not of same font style as the others
 - You can remove the ```#eventCol_1 {
    margin-inline: 20px;
}``` from  `ClubsPage.css` , line 280
- Make the changes on for devices upto `430px`

### Screenshots 

image

**Comment by ishaanbedi** [comment]
Alright! Thanks for highlighting this! Working on it.

**Comment by ishaanbedi** [comment]
Hi @IAmTamal , I've made the changes as you suggested! Can you please have a look?

**Comment by IAmTamal** [comment]
> Hi @IAmTamal , I've made the changes as you suggested! Can you please have a look? https://milan-qzerkqrer-iamtamal.vercel.app/

Hello there, you donot need to deploy the app again by yourself. vercel makes a preview !
- The `h1` is still not `32px`
- The last line is not of the same style, weight, color as that of the above

image

You need to fix these !

**Pull request closed without merging**
