### PR TITLE
Forgot password page design 🛠

### LINKED ISSUE #396: Forgot password page design
### Description

I can design forgot password page please assignment currently on clicking nothing its working.

### Screenshots

_No response_

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nishtha53**
# Fixes Issue

**My PR closes #396 *

# Changes proposed
- Created forgot password design for club.
- Create forgot password design for user

## What were you told to do ?

- Need to come with good design for forgot password

## What did you do ?
- Created a forgot password design for club and user which takes email field and forgot password button

# Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

# Screenshots
image
image

### CODE REVIEW

**Comment by IAmTamal** [comment]
@nishtha53 Replace ✅ with [X] in your PR - this helps the checks to pass.

**Comment by nishtha53** [comment]
@IAmTamal changed ✅

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image

Please move the thing up by a little bit , seems like a blank empty space on the top !

Rename the file from `ForgotPasswordClub.jsx` to `ClubForgotpassword.jsx`
Rename the file from `UserForgotPassword.jsx` to `UserForgotpassword.jsx`

**Comment by nishtha53** [comment]
Okay sure will do following changes!

**Comment by nishtha53** [comment]
@IAmTamal changes are done which you mentioned.

**Comment by IAmTamal** [comment]
Do let me know once done
PS : IF the deployment fails that means your code has errors like typos, filenames etc

**Comment by nishtha53** [comment]
@IAmTamal I have just changed file name but updated well everywhere. Then why deployment fails?

**Comment by IAmTamal** [comment]
> @IAmTamal I have just changed file name but updated well everywhere. Then why deployment fails?

image

**Comment by nishtha53** [comment]
@IAmTamal 
image
it is proper in local. Let me do changes and try again.

**Comment by nishtha53** [comment]
image

Both files name are right.
image
image

Also running fine in my PC.

**Comment by IAmTamal** [comment]
@nishtha53 haha tricky thing 😂
Whenever you make changes to filename in local, they are not changed in GitHub. 
You need to come to github, go to your repo and then change the name from there. 

Anyways, merging it !

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Comment by nishtha53** [comment]
ohh i get to know this new thing today😅
I will take care from next time.

Thankyou for merging PR: )

**Pull request merged**
