### PR TITLE
Fixed the Date and Time sections of Create event 

### LINKED ISSUE #350: Dates are not Mentioned
### Description

In the Event Section , the Time for 'HOLA PETS' event is not mentioned which can confuse users is to when to attend event since there is one more event at same place like - one is at 11a.m

### Screenshots

Time is not mentioned for 'HOLA PETS' event : 

milan_time

Hey @IAmTamal  can you please assign this issue to me, I would love to fix this for HACKTOBERFEST

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DhruvRathi2001**
# Issue  📐

- **I <your name here> have worked for #350**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes  #350**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
 Hey @IAmTamal  I have Added the Date and Time section of the Create Event :

 
  
milan_event

---

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by DhruvRathi2001** [comment]
Fixed issue #350

**Comment by IAmTamal** [comment]
@DhruvRathi2001 always mention the issue in PR , 
image

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
