### PR TITLE
Fix : Added the link to Footer correctly

### LINKED ISSUE #346: Links not Working
### Description

Here the links to Twitter and Facebook are not Working and are redirecting us to the same page.

links

Hey @IAmTamal  can you please assign this issue to me, I would love to fix it for HACKTOBERFEST.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DhruvRathi2001**
# Issue  📐

- **I <your name here> have worked for #346**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #346**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
  
  Added link to Github correctly :

milan_final

---

Hey @IAmTamal  I made the changes you told please review it.

### CODE REVIEW

**Review by IAmTamal — COMMENTED** [review]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the pull request soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by DhruvRathi2001** [comment]
fixed issue #346

**Comment by IAmTamal** [comment]
@DhruvRathi2001 Please make one single PR. 
There are 2 PRS currently.

**Comment by DhruvRathi2001** [comment]
@IAmTamal  yes I closed one PR.

**Pull request merged**
