### PR TITLE
fix bug shop page responsive

### LINKED ISSUE #525: [BUGS] Shop page Mobile responsiveness
### Description

- if you take a look at the screenshot 1 you will notice that there is an image, above the `Welcome to our store !`, remove that for mobiles
- The paragraph `We aim at selling.....` has a less width in mobiles, make it so that more amount of screen space is covered in terms of width !

## Screenshot

image

### Additional information

_No response_

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

### PR DESCRIPTION
**Pull request by srijoy-paul**
# Fixes Issue #525 

**My PR closes #525 **
Closes #525 

# Changes proposed

## What were you told to do ?

The issue was to make the shop page responsive for mobile devices:
1. have to remove the image in the header, in small screen devices.
2. Increase the width of an element to take more space, while in small screen devices.

## What did you do ?

1. for the first task, I have made the display none of the img element in shops page.
2.  for the second task, increased the width of the element, and increase the letter spacing.

---

# Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

# Screenshots

image

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
- Your changes looks fantastic, can i request something more ? 
- Can we have the size of the heading a little bit more increased for mobiles ? 


image

**Comment by srijoy-paul** [comment]
Sure @IAmTamal will work on this

**Comment by srijoy-paul** [comment]
@IAmTamal Hope this works
image

**Review by IAmTamal — APPROVED** [review]
## Looks good to me ✅

- **⚒ Thankyou for working on the issue**
- **⭐ Do star the repo, to get updates on more issues !**
- **💚 Keep contributing to Opensource**

**Pull request merged**
