### PR TITLE
UI/UX Improvements - Homepage sections 

### LINKED ISSUE #207: Improvement in the donation and event section's design
### improvement in UI

It would be great if there will be a icon in the explore button just like share your love button and also some hover effect like the buttons in the club and user buttons. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Harsh3363**
# Issue  📐

- **I <your name here> have added explore icon and hover effect in the donation and event jsx and css files**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #207 **

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
Screenshot (80)

Screenshot (81)

  
  
---

### CODE REVIEW

**Comment by IAmTamal** [comment]
This addition looks awesome , always raise an issue before PRs.
Make an issue , relevant to this PR, i'll merge this after you've done that !

**Comment by Harsh3363** [comment]
Sure

**Comment by Harsh3363** [comment]
Made the changes as requested

**Review by IAmTamal — APPROVED** [review]
Checked ✅

**Comment by IAmTamal** [comment]
Sorry i was a bit busy , will check and merge it RN  !

**Pull request merged**
